# Generated by Django 6.1 on 2026-08-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('current_step', models.CharField(choices=[('GREETING', 'Saludo inicial'), ('AWAITING_CEDULA', 'Esperando cedula'), ('MENU', 'Menu de opciones'), ('AWAITING_IMAGE', 'Esperando imagen del recibo'), ('CONFIRMING', 'Confirmando datos extraidos'), ('DONE', 'Conversacion finalizada')], default='GREETING', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='drivers.driver')),
                ('pending_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_in_sessions', to='expenses.expense')),
            ],
        ),
    ]
