# Generated by Django 6.1 on 2026-08-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(help_text='Número de cédula del conductor (identificador único)', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
